### ISSUE TITLE
Effizienz

### ISSUE THREAD

**Issue by pleink** [fhnw-oopI2/fs20-l06-ab-pleink#1]
Gibt es in AB 3 einen effizienteren Weg das Margin den Buttons zuzuordnen?

**Comment by fhnw-webec** [comment]
Nein, nicht das ich wüsste (ohne XML und CSS).

Das API ist diese statische setMargin Methode und die Möglichkeit die Offsets zu setzen ist die Insets-Klasse. 

Mit CSS könnte man Klassen definieren und diese wiederverwenden. Wir werden das aber nicht behandeln, da wir noch andere Themen anschauen werden (IO, Threads). Aber Sie können dieses Thema natürlich auf eigene Faust erforschen :-) . Ich meine im IP2 Projekt haben Sie das doch schon eingesetzt.
